# Generated by Django 4.1.4 on 2022-12-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile',
            new_name='account',
        ),
    ]
